# üèÜ EDA para Dashboarding - Proyecto Consumo global de Energ√≠a

üîç **Objetivo:**  
"Este an√°lisis exploratorio busca entender la distribuci√≥n de los datos del dataset de energ√≠a global de la plataforma Our World in Data y obtener la informaci√≥n necesaria para aplicarlo en el desarrollo de un dashboard con Dash

üìä **Fuente de datos:** [`owid-energy-data.csv`]

## 1Ô∏è‚É£ üìÇ Carga de Datos y Configuraci√≥n Inicial

In [22]:
# Libraries
import pandas as pd
import numpy as np

# Read dataset
df = pd.read_csv('../data/owid-energy-data.csv')

# List first rows
df.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy,carbon_intensity_elec,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy,electricity_demand,electricity_demand_per_capita,electricity_generation,electricity_share_energy,energy_cons_change_pct,energy_cons_change_twh,energy_per_capita,energy_per_gdp,fossil_cons_change_pct,fossil_cons_change_twh,fossil_elec_per_capita,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,fossil_share_energy,gas_cons_change_pct,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,gas_prod_change_pct,gas_prod_change_twh,gas_prod_per_capita,gas_production,gas_share_elec,gas_share_energy,greenhouse_gas_emissions,hydro_cons_change_pct,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,hydro_share_elec,hydro_share_energy,low_carbon_cons_change_pct,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_elec_per_capita,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,low_carbon_share_energy,net_elec_imports,net_elec_imports_share_demand,nuclear_cons_change_pct,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,nuclear_share_energy,oil_cons_change_pct,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,oil_prod_change_pct,oil_prod_change_twh,oil_prod_per_capita,oil_production,oil_share_elec,oil_share_energy,other_renewable_consumption,other_renewable_electricity,other_renewable_exc_biofuel_electricity,other_renewables_cons_change_pct,other_renewables_cons_change_twh,other_renewables_elec_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_energy_per_capita,other_renewables_share_elec,other_renewables_share_elec_exc_biofuel,other_renewables_share_energy,per_capita_electricity,primary_energy_consumption,renewables_cons_change_pct,renewables_cons_change_twh,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,renewables_share_elec,renewables_share_energy,solar_cons_change_pct,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.87,1.550,NaN,569.557,NaN,NaN,NaN,NaN,NaN,76.03,NaN,NaN,NaN,NaN,20.081,NaN,378.61,NaN,378.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305.36,NaN,NaN,80.653,NaN,NaN,NaN,NaN,NaN,164.26,NaN,NaN,NaN,NaN,NaN,43.385,NaN,215.64,NaN,NaN,NaN,NaN,50.45,NaN,13.325,NaN,NaN,NaN,NaN,NaN,73.25,NaN,19.347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,65.07,NaN,NaN,NaN,NaN,NaN,17.187,NaN,NaN,22.80,16.93,NaN,NaN,NaN,NaN,NaN,6.022,4.472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.25,NaN,19.347,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.46,1.596,NaN,567.642,NaN,NaN,NaN,NaN,NaN,86.26,NaN,NaN,NaN,NaN,21.307,NaN,404.85,NaN,404.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,327.66,NaN,NaN,80.934,NaN,NaN,NaN,NaN,NaN,190.41,NaN,NaN,NaN,NaN,NaN,47.032,NaN,229.81,NaN,NaN,NaN,NaN,54.33,NaN,13.420,NaN,NaN,NaN,NaN,NaN,77.19,NaN,19.066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,50.99,NaN,NaN,NaN,NaN,NaN,12.595,NaN,NaN,22.86,16.40,NaN,NaN,NaN,NaN,NaN,5.647,4.051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.19,NaN,19.066,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.62,1.528,NaN,570.212,NaN,NaN,NaN,NaN,NaN,93.43,NaN,NaN,NaN,NaN,21.568,NaN,433.19,NaN,433.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,356.67,NaN,NaN,82.336,NaN,NaN,NaN,NaN,NaN,208.92,NaN,NaN,NaN,NaN,NaN,48.228,NaN,247.01,NaN,NaN,NaN,NaN,53.29,NaN,12.302,NaN,NaN,NaN,NaN,NaN,76.52,NaN,17.664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,54.32,NaN,NaN,NaN,NaN,NaN,12.540,NaN,NaN,23.23,16.61,NaN,NaN,NaN,NaN,NaN,5.363,3.834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.52,NaN,17.664,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.45,1.626,NaN,574.699,NaN,NaN,NaN,NaN,NaN,102.01,NaN,NaN,NaN,NaN,22.261,NaN,458.24,NaN,458.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381.84,NaN,NaN,83.328,NaN,NaN,NaN,NaN,NaN,226.51,NaN,NaN,NaN,NaN,NaN,49.430,NaN,263.35,NaN,NaN,NaN,NaN,53.21,NaN,11.612,NaN,NaN,NaN,NaN,NaN,76.40,NaN,16.672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,53.32,NaN,NaN,NaN,NaN,NaN,11.636,NaN,NaN,23.19,15.74,NaN,NaN,NaN,NaN,NaN,5.061,3.435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.40,NaN,16.672,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.40,1.692,NaN,581.420,NaN,NaN,NaN,NaN,NaN,115.01,NaN,NaN,NaN,NaN,23.161,NaN,496.56,NaN,496.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,418.60,NaN,NaN,84.300,NaN,NaN,NaN,NaN,NaN,244.16,NaN,NaN,NaN,NaN,NaN,49.170,NaN,288.71,NaN,NaN,NaN,NaN,52.99,NaN,10.671,NaN,NaN,NaN,NaN,NaN,77.96,NaN,15.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,59.43,NaN,NaN,NaN,NaN,NaN,11.968,NaN,NaN,24.97,16.57,NaN,NaN,NaN,NaN,NaN,5.029,3.337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.96,NaN,15.700,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

In [23]:
# Rows & Columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21812 entries, 0 to 21811
Columns: 130 entries, country to wind_share_energy
dtypes: float64(127), int64(1), object(2)
memory usage: 21.6+ MB

## 2Ô∏è‚É£ üîç An√°lisis de la Estructura del Dataset

In [26]:
# data types
df.dtypes

country                    object
year                        int64
iso_code                   object
population                float64
gdp                       float64
                           ...
wind_elec_per_capita      float64
wind_electricity          float64
wind_energy_per_capita    float64
wind_share_elec           float64
wind_share_energy         float64
Length: 130, dtype: object

In [27]:
# data types count
df.dtypes.value_counts()

float64    127
object       2
int64        1
Name: count, dtype: int64